# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not


In [2]:
import numpy as np
import random

In [22]:
import random
def new_matrix(a, b):
    M = np.zeros((a, b))
    for x in range(0, M.shape[0]):
        for y in range(0, M.shape[1]):
            M[x][y] = random.randrange(1, 9) 
    return(M)

In [27]:
A = new_matrix(4,4)
print('Matrix A:', "\n", A)
B = new_matrix(4,4)
print('Matrix B:',"\n", B)
C = new_matrix(4,4)
print('Matrix C:',"\n", C)

Matrix A: 
 [[6. 8. 6. 4.]
 [5. 2. 8. 2.]
 [6. 4. 1. 8.]
 [7. 6. 1. 2.]]
Matrix B: 
 [[3. 1. 3. 3.]
 [8. 2. 3. 6.]
 [1. 6. 4. 7.]
 [7. 6. 4. 3.]]
Matrix C: 
 [[7. 4. 3. 3.]
 [1. 8. 6. 5.]
 [4. 6. 5. 4.]
 [2. 7. 6. 5.]]


## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [28]:
# Your code here
#LHS
LHS = A.dot(B+C)
print("LHS", '\n', LHS)
#RHS
RHS = A.dot(B)+A.dot(C)
print("RHS", '\n', RHS)

LHS 
 [[198. 234. 202. 222.]
 [126. 167. 140. 156.]
 [173. 186. 161. 155.]
 [147. 133. 125. 135.]]
RHS 
 [[198. 234. 202. 222.]
 [126. 167. 140. 156.]
 [173. 186. 161. 155.]
 [147. 133. 125. 135.]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [29]:
# Your code here 
#LHS
LHS = A.dot(B.dot(C))
print("LHS", '\n', LHS)
#RHS
RHS = (A.dot(B)).dot(C)
print("RHS", '\n', RHS)

LHS 
 [[1462. 2452. 1970. 1686.]
 [ 862. 1753. 1412. 1193.]
 [1227. 1879. 1497. 1290.]
 [ 969. 1428. 1149.  991.]]
RHS 
 [[1462. 2452. 1970. 1686.]
 [ 862. 1753. 1412. 1193.]
 [1227. 1879. 1497. 1290.]
 [ 969. 1428. 1149.  991.]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [30]:
# Your code here 
#LHS
LHS = A.dot(B)
print("LHS", '\n', LHS)
#RHS
RHS = B.dot(A)
print("RHS", '\n', RHS)

LHS 
 [[116.  82.  82. 120.]
 [ 53.  69.  61.  89.]
 [107.  68.  66.  73.]
 [ 84.  37.  51.  70.]]
RHS 
 [[ 62.  56.  32.  44.]
 [118. 116.  73.  72.]
 [109.  78.  65.  62.]
 [117. 102.  97.  78.]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [60]:
import random
def new_vector(a):
    V = np.zeros([a])
    for x in range(0, V.shape[0]):
        V[x] = random.randrange(1, 9) 
    return(V)

In [61]:
x = new_vector(3)
y = new_vector(3)
print('Vector x:', '\n', x)
print('Vector y:', '\n', y)

Vector x: 
 [5. 2. 3.]
Vector y: 
 [5. 4. 6.]


In [66]:
y = np.array([[2, 4, 6]])
y

array([[2, 4, 6]])

In [68]:
np.transpose(y)

array([[2],
       [4],
       [6]])

In [67]:
x = np.array([[1,3,5]])
x

array([[1, 3, 5]])

In [69]:
np.transpose(x)

array([[1],
       [3],
       [5]])

In [72]:
# Your code here 
#A_transposed = A.T
#A_transposed_2 = np.transpose(A)

#LHS
LHS = np.transpose(x)*y
print("LHS:", '\n', LHS)
#RHS
RHS = np.transpose(y)*x
print("RHS:", '\n', RHS)


LHS: 
 [[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]
RHS: 
 [[ 2  6 10]
 [ 4 12 20]
 [ 6 18 30]]


In [73]:
# Your code here 
#A_transposed = A.T
#A_transposed_2 = np.transpose(A)

#LHS
LHS = np.transpose(x).dot(y)
print("LHS:", '\n', LHS)
#RHS
RHS = np.transpose(y).dot(x)
print("RHS:", '\n', RHS)


LHS: 
 [[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]
RHS: 
 [[ 2  6 10]
 [ 4 12 20]
 [ 6 18 30]]


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [74]:
# Your code here 
print(A, '\n')
print(B, '\n')
#LHS
LHS = (A.dot(B)).T
print("LHS", '\n', LHS)
#RHS
RHS = (B.T).dot(A.T)
print("RHS", '\n', RHS)

[[6. 8. 6. 4.]
 [5. 2. 8. 2.]
 [6. 4. 1. 8.]
 [7. 6. 1. 2.]] 

[[3. 1. 3. 3.]
 [8. 2. 3. 6.]
 [1. 6. 4. 7.]
 [7. 6. 4. 3.]] 

LHS 
 [[116.  53. 107.  84.]
 [ 82.  69.  68.  37.]
 [ 82.  61.  66.  51.]
 [120.  89.  73.  70.]]
RHS 
 [[116.  53. 107.  84.]
 [ 82.  69.  68.  37.]
 [ 82.  61.  66.  51.]
 [120.  89.  73.  70.]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 

In [75]:
import numpy as np


# Distributive

A = np.array([[2, 3], [1, 4], [7, 6]])
B = np.array([[5], [2]])
C = np.array([[4], [3]])

left = A.dot(B + C)
right = A.dot(B) + A.dot(C)

print (left == right)

[[ True]
 [ True]
 [ True]]


In [76]:

# Associative

A = np.array([[2, 3], [1, 4], [7, 6]])
B = B = np.array([[5, 3], [2, 2]])
C = np.array([[4], [3]])

left = A.dot(B.dot(C))
right = (A.dot(B)).dot(C)

left == right

array([[ True],
       [ True],
       [ True]])

In [77]:

# Commutative

A = np.array([[2, 3], [6, 5]])
B = np.array([[5, 3], [2, 2]])

left = A.dot(B)
right = B.dot(A)

print(left)
print(right)

left == right

[[16 12]
 [40 28]]
[[28 30]
 [16 16]]


array([[False, False],
       [False, False]])

In [78]:

# Vector Commutative

x = np.array([[2], [6], [7]])
y = np.array([[3], [5], [9]])

left = np.transpose(x).dot(y)
right = np.transpose(y).dot(x)
left == right

array([[ True]])

In [79]:

# Matrix

A = np.array([[2, 13], [1, 4], [72, 6], [18, 12], [27,5]])
B = np.array([[5, 30], [22, 2]])

left = np.transpose(A.dot(B))
right = np.transpose(B).dot(np.transpose(A))
left == right

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])